import smtplib
import ssl
from email.message import EmailMessage
# Configuration
SENDER_EMAIL = ""
SENDER_PASSWORD = ""
RECEIVER_EMAIL = ""
SMTP_SERVER = ""
PORT = 587

def send_simple_email(subject: str, body: str, receiver_email: str, sender_name: str = "Christopher-Python"):
    """
    Sends plain text email using EmailMessage class

    Args:
    subject (str): Subject line
    body (str): Text content of email
    receiver_email (str): email of recipient
    sender_name (str): Name to use for the 'from' header
    """

    try:
        #Create secure SSL connection
        context = ssl.create_default_context()

        #1. Make email message object
        message = EmailMessage()
        message["Subject"] = subject
        message["From"] = f"{sender_name} <{SENDER_EMAIL}>"
        message["To"] = receiver_email

        #Set content of email
        message.set_content(body)

        #2. Connect to SMTP server to send email
        print(f"Attempting to connect to {SMTP_SERVER} on port {PORT}...")

        with smtplib.SMTP(SMTP_SERVER, PORT) as server:
            # Start TLS encryption
            server.starttls(context=context)
            #Login
            server.login(SENDER_EMAIL, SENDER_PASSWORD)
            # Use send_message() for EmailMessage object
            server.send_message(message)

            print(f"Success! Email sent to {receiver_email} with subject: '{subject}'")

    except smtplib.SMTPAuthenticationError:
        print("\nERROR: Failed to log in to the SMTP server.")
        print("CRITICAL: Ensure SENDER_PASSWORD is an 'App Password' generated by your email provider.")
    except smtplib.SMTPException as e:
        print(f"\nERROR: An SMTP error occurred: {e}")
    except Exception as e:
        print(f"\nERROR: An unexpected error occurred: {e}")

if __name__ == "__main__":
    #Define content for email
    recipient_name = "Recipient User"

    email_subject = "Test Email from Python Script"
    email_body = f"""Dear {recipient_name},

This is a test email sent automatically from a Python Script.
Regards,
Automated Follow-up System
"""
    
    send_simple_email(email_subject, email_body, RECEIVER_EMAIL)